version: "1.0"

services:
  face-rec:
    build: .
    ports:
      - "8889:8888"
    volumes:
      - .:/jlabs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]